channels:
  - conda-forge
dependencies:
  - python==3.6
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - sphinx_rtd_theme
  - nbsphinx
  - gdal
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - h5py
  - deprecation
  - pip:
    - sphinxcontrib-bibtex
    - git+https://github.com/wradlib/wradlib.git@strip1.0.0