channels:
  - conda-forge
dependencies:
  - python==3.6
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - nbsphinx
  - numpy
  - deprecation
  - git
